### PR TITLE
Improve level validation and canonicalisation logic (updated)

### PR DESCRIPTION
**Pull request by kyzn**
Hi Dave! Please find attached pull request, that is based on #34. You had requested a few changes there, I went ahead and replaced eval with Try::Tiny and wrote some tests.

Let me know if there's anything I should update.
Thanks!

[\#cpan-prc](http://cpan-prc.org/)

### CODE REVIEW

**Comment by preaction** [comment]
Thanks for the patch! Of the changes @autarch mentioned needing in #34, the only thing that isn't quite right is that the Changes entry doesn't mention Kerin Millar's name for the patch (and now your name, too, for writing tests and cleaning it up). Once that is done, then this should be able to be merged.

**Comment by kyzn** [comment]
Hi @preaction, thanks for your comment! I updated Changes per your comment. Let me know if it looks good.

**Comment by autarch** [comment]
Merged from the CLI. Thanks!

Closes #34.

**Comment by kerframil** [comment]
@kyzn Thanks for picking this up and rendering it fit for inclusion.

**Pull request closed without merging**
